# LICENSE HEADER MANAGED BY add-license-header
#
# Copyright (C) 2025 Ethorbit
#
# This file is part of SoundPrompt.
#
# SoundPrompt is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3
# of the License, or (at your option) any later version.
#
# SoundPrompt is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the
# GNU General Public License along with SoundPrompt.
# If not, see <https://www.gnu.org/licenses/>.
#

[general]
model_name = "all-MiniLM-L6-v2"
device = "cpu" # Set to "cuda" for better performance (only if you have a modern GPU)
# TODO: raranker_model = "cross-encoder/ms-marco-MiniLM-L-6-v2"

[database]
directory = "output"
save_filenames = false  # WARNING if you use this: ALL your files must be named with real words or you'll get unpredictable results
