# LICENSE HEADER MANAGED BY add-license-header
#
# Copyright (C) 2025 Ethorbit
#
# This file is part of SoundPrompt.
#
# SoundPrompt is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3
# of the License, or (at your option) any later version.
#
# SoundPrompt is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the
# GNU General Public License along with SoundPrompt.
# If not, see <https://www.gnu.org/licenses/>.
#


# DISCLAIMER:
# This container ONLY WORKS AS-IS ON: Linux + X11 + Pulseaudio
#   You need to run xhost +SI:localuser:YOURUSERNAME
#   for hotkey functionality
# CHANGES ARE NEEDED IF YOUR SETUP IS ANY DIFFERENT!!


x-shared: &shared
  group_add:
    - audio
  environment:
    - DISPLAY=${DISPLAY}
    - PULSE_SERVER=unix:/run/user/${UID:-1000}/pulse/native
  devices:
    - "nvidia.com/gpu=all"
    - "/dev/dri:/dev/dri"
    - "/dev/snd:/dev/snd"

x-build: &build
  context: .    
  args:
    UID: ${UID:-1000}
    GID: ${GID:-1000}

x-develop: &develop
  build:
    <<: [ *build ]
    target: develop
  volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix
    - /run/user/${UID:-1000}/pulse:/run/user/${UID:-1000}/pulse
    - .:/app
    - .cache:/home/python/.cache
    - ./input:/input:ro
    - ./output:/output


services:
  pre-commit:
    profiles:
      - pre-commit
    <<: [ *shared, *develop ]
    entrypoint: python
    command: /usr/local/bin/pre-commit
  develop:
    profiles:
      - develop
    <<: [ *shared, *develop ]
    stdin_open: true
    tty: true


  app:
    profiles:
      - app
    <<: [ *shared ]
    build:
      <<: [ *build ]
      target: app
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /run/user/${UID:-1000}/pulse:/run/user/${UID:-1000}/pulse
      - .cache:/home/python/.cache
      - ./input:/input:ro
      - ./output:/output
